[repository]
# Repository name. Shown by `hyprpm list`; used by `hyprpm remove`.
name = "hyprmacs-keymap"
authors = ["11xx"]

# Plugin name. This is what `hyprpm list`/`hyprpm enable` use.
[hyprmacs-keymap]
description = "Emacs-like keymap helper Hyprland plugin"
authors = ["11xx"]
output = "hyprmacs-keymap.so"
build = [
  "make all"
]
